/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CategoryResponse } from '../models/category-response';
import { createCategory } from '../fn/category/create-category';
import { CreateCategory$Params } from '../fn/category/create-category';
import { deleteCategory } from '../fn/category/delete-category';
import { DeleteCategory$Params } from '../fn/category/delete-category';
import { findAllCategories } from '../fn/category/find-all-categories';
import { FindAllCategories$Params } from '../fn/category/find-all-categories';
import { findCategoryById } from '../fn/category/find-category-by-id';
import { FindCategoryById$Params } from '../fn/category/find-category-by-id';
import { PageResponseCategoryResponse } from '../models/page-response-category-response';
import { updateCategory } from '../fn/category/update-category';
import { UpdateCategory$Params } from '../fn/category/update-category';


/**
 * Category API
 */
@Injectable({ providedIn: 'root' })
export class CategoryService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findCategoryById()` */
  static readonly FindCategoryByIdPath = '/api/v1/categories/{category-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findCategoryById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findCategoryById$Response(params: FindCategoryById$Params, context?: HttpContext): Observable<StrictHttpResponse<CategoryResponse>> {
    const obs = findCategoryById(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findCategoryById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findCategoryById(params: FindCategoryById$Params, context?: HttpContext): Observable<CategoryResponse> {
    const resp = this.findCategoryById$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<CategoryResponse>): CategoryResponse => r.body)
    );
  }

  /** Path part for operation `updateCategory()` */
  static readonly UpdateCategoryPath = '/api/v1/categories/{category-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateCategory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCategory$Response(params: UpdateCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = updateCategory(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateCategory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCategory(params: UpdateCategory$Params, context?: HttpContext): Observable<void> {
    const resp = this.updateCategory$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deleteCategory()` */
  static readonly DeleteCategoryPath = '/api/v1/categories/{category-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteCategory()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCategory$Response(params: DeleteCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = deleteCategory(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteCategory$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCategory(params: DeleteCategory$Params, context?: HttpContext): Observable<void> {
    const resp = this.deleteCategory$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `findAllCategories()` */
  static readonly FindAllCategoriesPath = '/api/v1/categories';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllCategories()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllCategories$Response(params?: FindAllCategories$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseCategoryResponse>> {
    const obs = findAllCategories(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllCategories$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllCategories(params?: FindAllCategories$Params, context?: HttpContext): Observable<PageResponseCategoryResponse> {
    const resp = this.findAllCategories$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PageResponseCategoryResponse>): PageResponseCategoryResponse => r.body)
    );
  }

  /** Path part for operation `createCategory()` */
  static readonly CreateCategoryPath = '/api/v1/categories';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createCategory()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCategory$Response(params: CreateCategory$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = createCategory(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createCategory$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createCategory(params: CreateCategory$Params, context?: HttpContext): Observable<void> {
    const resp = this.createCategory$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
