/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createStockMvt } from '../fn/stock-mvt/create-stock-mvt';
import { CreateStockMvt$Params } from '../fn/stock-mvt/create-stock-mvt';
import { deleteStockMvt } from '../fn/stock-mvt/delete-stock-mvt';
import { DeleteStockMvt$Params } from '../fn/stock-mvt/delete-stock-mvt';
import { findAllStockMvts } from '../fn/stock-mvt/find-all-stock-mvts';
import { FindAllStockMvts$Params } from '../fn/stock-mvt/find-all-stock-mvts';
import { findAllStockMvtsByProductId } from '../fn/stock-mvt/find-all-stock-mvts-by-product-id';
import { FindAllStockMvtsByProductId$Params } from '../fn/stock-mvt/find-all-stock-mvts-by-product-id';
import { findStockMvtById } from '../fn/stock-mvt/find-stock-mvt-by-id';
import { FindStockMvtById$Params } from '../fn/stock-mvt/find-stock-mvt-by-id';
import { PageResponseStockMvtResponse } from '../models/page-response-stock-mvt-response';
import { StockMvtResponse } from '../models/stock-mvt-response';
import { updateStockMvt } from '../fn/stock-mvt/update-stock-mvt';
import { UpdateStockMvt$Params } from '../fn/stock-mvt/update-stock-mvt';


/**
 * Stock Mvt API
 */
@Injectable({ providedIn: 'root' })
export class StockMvtService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `findStockMvtById()` */
  static readonly FindStockMvtByIdPath = '/api/v1/stocks/{stock-mvt-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findStockMvtById()` instead.
   *
   * This method doesn't expect any request body.
   */
  findStockMvtById$Response(params: FindStockMvtById$Params, context?: HttpContext): Observable<StrictHttpResponse<StockMvtResponse>> {
    const obs = findStockMvtById(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findStockMvtById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findStockMvtById(params: FindStockMvtById$Params, context?: HttpContext): Observable<StockMvtResponse> {
    const resp = this.findStockMvtById$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<StockMvtResponse>): StockMvtResponse => r.body)
    );
  }

  /** Path part for operation `updateStockMvt()` */
  static readonly UpdateStockMvtPath = '/api/v1/stocks/{stock-mvt-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateStockMvt()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateStockMvt$Response(params: UpdateStockMvt$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = updateStockMvt(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateStockMvt$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateStockMvt(params: UpdateStockMvt$Params, context?: HttpContext): Observable<void> {
    const resp = this.updateStockMvt$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `deleteStockMvt()` */
  static readonly DeleteStockMvtPath = '/api/v1/stocks/{stock-mvt-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteStockMvt()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteStockMvt$Response(params: DeleteStockMvt$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = deleteStockMvt(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteStockMvt$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteStockMvt(params: DeleteStockMvt$Params, context?: HttpContext): Observable<void> {
    const resp = this.deleteStockMvt$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `findAllStockMvts()` */
  static readonly FindAllStockMvtsPath = '/api/v1/stocks';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllStockMvts()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllStockMvts$Response(params?: FindAllStockMvts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseStockMvtResponse>> {
    const obs = findAllStockMvts(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllStockMvts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllStockMvts(params?: FindAllStockMvts$Params, context?: HttpContext): Observable<PageResponseStockMvtResponse> {
    const resp = this.findAllStockMvts$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PageResponseStockMvtResponse>): PageResponseStockMvtResponse => r.body)
    );
  }

  /** Path part for operation `createStockMvt()` */
  static readonly CreateStockMvtPath = '/api/v1/stocks';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createStockMvt()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createStockMvt$Response(params: CreateStockMvt$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = createStockMvt(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createStockMvt$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createStockMvt(params: CreateStockMvt$Params, context?: HttpContext): Observable<void> {
    const resp = this.createStockMvt$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `findAllStockMvtsByProductId()` */
  static readonly FindAllStockMvtsByProductIdPath = '/api/v1/stocks/product/{product-id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findAllStockMvtsByProductId()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllStockMvtsByProductId$Response(params: FindAllStockMvtsByProductId$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseStockMvtResponse>> {
    const obs = findAllStockMvtsByProductId(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findAllStockMvtsByProductId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findAllStockMvtsByProductId(params: FindAllStockMvtsByProductId$Params, context?: HttpContext): Observable<PageResponseStockMvtResponse> {
    const resp = this.findAllStockMvtsByProductId$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PageResponseStockMvtResponse>): PageResponseStockMvtResponse => r.body)
    );
  }

}
