events {}

http {
    include /etc/nginx/mime.types;  
    # ✅ moved here — applies globally

    server {
        listen 80;                  
        
        # # ✅ API proxy — must be FIRST before catch-all regex
        # location /api/ {
        #     proxy_pass http://saas-app-api:8080/api/;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #     proxy_set_header X-Forwarded-Proto $scheme;
        #     proxy_pass_request_headers on;
        #     proxy_pass_request_body on;
        # }

        # Main location
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Handle JS | CSS files with correct MIME type
        location ~ \.(js|css)$ {
            root /usr/share/nginx/html;
            include /etc/nginx/mime.types;  
        }

        # Catch all — handle refreshes on any route
        location ~ ^/.+$ {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # ✅ Proxy all API calls — no CORS, no port issues
      #   location /api/ {  
      #       proxy_pass http://saas-app-api:8080/api/;  
      #       # container name:internal port
      #       proxy_set_header Host $host;
      #       proxy_set_header X-Real-IP $remote_addr;
      #       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      #       # ✅ Add these
      #       proxy_method POST;                          
      #       proxy_pass_request_headers on;              
      #       proxy_pass_request_body on; 
      # }
    }
}


# location /              → handles all base requests
#                           e.g. /, /home, /about

# location ~ \.(js|css)$  → handles static assets
#                           e.g. main.js, styles.css

# location ~ ^/.+$        → catches all other routes
#                           e.g. /products, /about/123
#                           prevents 404 on page refresh










# events {}

# http {
#     server {
#         listen:80;

#         location / {
#           root /usr/share/nginx/html;
#           index index.html;
#           try_files $uri $uri/ /index.html;
#         }

# #         Handle javascript | CSS files with correct MIME type

#         location ~ \.(js|css)$ {
#           root /usr/share/nginx/html;
#           include /etc/nginx/mime.type;
#         }

# #         Catch all locations to handle refreshes on any route
#         location ~ ^/.+$ {
#           root /usr/share/nginx/html;
#           index index.html;
#           try_files $uri $uri/ /index.html;
#         }
#     }
# }
