/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseStockMvtResponse } from '../../models/page-response-stock-mvt-response';

export interface FindAllStockMvts$Params {
  page?: number;
  size?: number;
}

export function findAllStockMvts(http: HttpClient, rootUrl: string, params?: FindAllStockMvts$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseStockMvtResponse>> {
  const rb = new RequestBuilder(rootUrl, findAllStockMvts.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseStockMvtResponse>;
    })
  );
}

findAllStockMvts.PATH = '/api/v1/stocks';
