/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { StockMvtRequest } from '../../models/stock-mvt-request';

export interface UpdateStockMvt$Params {
  'stock-mvt-id': string;
      body: StockMvtRequest
}

export function updateStockMvt(http: HttpClient, rootUrl: string, params: UpdateStockMvt$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, updateStockMvt.PATH, 'put');
  if (params) {
    rb.path('stock-mvt-id', params['stock-mvt-id'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

updateStockMvt.PATH = '/api/v1/stocks/{stock-mvt-id}';
