/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageResponseTenantResponse } from '../../models/page-response-tenant-response';

export interface FindAllTenants$Params {
  page?: number;
  size?: number;
}

export function findAllTenants(http: HttpClient, rootUrl: string, params?: FindAllTenants$Params, context?: HttpContext): Observable<StrictHttpResponse<PageResponseTenantResponse>> {
  const rb = new RequestBuilder(rootUrl, findAllTenants.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageResponseTenantResponse>;
    })
  );
}

findAllTenants.PATH = '/api/v1/tenants';
