/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CategoryRequest } from './models/category-request';
export type { CategoryResponse } from './models/category-response';
export type { LoginRequest } from './models/login-request';
export type { LoginResponse } from './models/login-response';
export type { PageResponseCategoryResponse } from './models/page-response-category-response';
export type { PageResponseProductResponse } from './models/page-response-product-response';
export type { PageResponseStockMvtResponse } from './models/page-response-stock-mvt-response';
export type { PageResponseTenantResponse } from './models/page-response-tenant-response';
export type { PageResponseUserResponse } from './models/page-response-user-response';
export type { ProductRequest } from './models/product-request';
export type { ProductResponse } from './models/product-response';
export type { RegisterTenantRequest } from './models/register-tenant-request';
export type { StockMvtRequest } from './models/stock-mvt-request';
export type { StockMvtResponse } from './models/stock-mvt-response';
export type { TenantResponse } from './models/tenant-response';
export type { UserRequest } from './models/user-request';
export type { UserResponse } from './models/user-response';
