/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TenantResponse } from '../models/tenant-response';
export interface PageResponseTenantResponse {
  content?: Array<TenantResponse>;
  first?: boolean;
  hasNext?: boolean;
  hasPrevious?: boolean;
  last?: boolean;
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
