/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StockMvtResponse } from '../models/stock-mvt-response';
export interface PageResponseStockMvtResponse {
  content?: Array<StockMvtResponse>;
  first?: boolean;
  hasNext?: boolean;
  hasPrevious?: boolean;
  last?: boolean;
  page?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
