/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductResponse {
  alertThreshold?: number;
  availableQuantity?: number;
  categoryId?: string;
  categoryName?: string;
  description?: string;
  id?: string;
  name?: string;
  price?: number;
  reference?: string;
}
