/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductRequest {
  alertThreshold?: number;
  categoryId: string;
  description?: string;
  name: string;
  price?: number;
  reference: string;
}
