/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterTenantRequest {
  adminEmail: string;
  adminFullName: string;
  adminPassword: string;
  adminUsername: string;
  companyCode: string;
  companyName: string;
  email: string;
}
