/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StockMvtResponse {
  comment?: string;
  dateMvt?: string;
  id?: string;
  quantity?: number;
  typeMvt?: 'IN' | 'OUT';
}
