/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TenantResponse {
  adminEmail?: string;
  adminFullName?: string;
  adminPassword?: string;
  adminUsername?: string;
  companyCode?: string;
  companyName?: string;
  createdAt?: string;
  email?: string;
  status?: 'PENDING' | 'ACTIVE' | 'SUSPENDED' | 'INACTIVE';
  tenantId?: string;
}
