/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRequest {
  email: string;
  firstName: string;
  lastName: string;
  password: string;
  role: 'ROLE_PLATFORM_ADMIN' | 'ROLE_COMPANY_ADMIN' | 'ROLE_ADMINISTRATOR' | 'ROLE_USER' | 'ROLE_SALES_OPERATOR';
  username: string;
}
